trigger:
- main

pool:
  name: MyLinux
  demands:
    - agent.name -equals myAgent

variables:
  - group: task-1-variable-group  # Must include variable: storageAccountName and other secrets

stages:
- stage: Plan
  displayName: 'Terraform Plan'
  jobs:
  - job: TerraformPlan
    displayName: 'Terraform Plan'
    steps:
    # Install unzip if not present
    - script: |
        sudo apt-get update && sudo apt-get install -y unzip
      displayName: 'Install unzip'
      workingDirectory: $(System.DefaultWorkingDirectory)

    # Install Terraform using a script step
    - script: |
        #!/bin/bash
        set -euo pipefail
        TERRAFORM_VERSION="1.3.0"
        echo "Downloading Terraform version ${TERRAFORM_VERSION}..."
        curl -fsSL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -o terraform.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        rm terraform.zip
        terraform version

        
      displayName: 'Install Terraform'
      workingDirectory: $(System.DefaultWorkingDirectory)

    # Initialize Terraform with backend config override
    - script: |
        terraform init -reconfigure\
          -backend-config="storage_account_name=$(storageAccountName)"
        #terraform state rm module.network.azurerm_resource_group.rg #remove from state file
        #terraform force-unlock -force ec22c6a3-2aa9-f8f9-5577-dce61fc5bf49 # forse state unlock 
      displayName: 'Terraform Init'
      workingDirectory: $(System.DefaultWorkingDirectory)
    # Initialize Terraform with backend config override
    # terraform state rm module.network.azurerm_resource_group.r
    - script: |
        echo "fromstate rm can be here"
      #remove from state file
      # forse state unlock 
      displayName: 'Terraform remove item'
      workingDirectory: $(System.DefaultWorkingDirectory)

    # Run Terraform plan and output the plan file
    - script: |
        terraform plan -out=tfplan \
          -var="client_id=$(client_id)" \
          -var="client_secret=$(client_secret)" \
          -var="subscription_id=$(subscription_id)" \
          -var="tenant_id=$(tenant_id)"
      displayName: 'Terraform Plan'
      workingDirectory: $(System.DefaultWorkingDirectory)

    # List files to verify the tfplan exists
    - script: |
        ls -al $(System.DefaultWorkingDirectory)
      displayName: 'Verify tfplan exists'
      workingDirectory: $(System.DefaultWorkingDirectory)

    # Publish the tfplan artifact for use in the Deploy stage
    - publish: $(System.DefaultWorkingDirectory)/tfplan
      artifact: tfplan
      displayName: 'Publish tfplan artifact'

- stage: Deploy
  displayName: 'Terraform Apply'
  dependsOn: Plan
  condition: succeeded()
  jobs:
  - job: TerraformApply
    displayName: 'Terraform Apply'
    steps:
    # Install unzip on the deploy agent
    - script: |
        sudo apt-get update && sudo apt-get install -y unzip
      displayName: 'Install unzip'
      workingDirectory: $(System.DefaultWorkingDirectory)

    # Re-install Terraform on the deploy agent
    - script: |
        #!/bin/bash
        set -euo pipefail
        TERRAFORM_VERSION="1.3.0"
        echo "Downloading Terraform version ${TERRAFORM_VERSION}..."
        curl -fsSL "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip" -o terraform.zip
        unzip terraform.zip
        sudo mv terraform /usr/local/bin/
        rm terraform.zip
        terraform version
      displayName: 'Install Terraform'
      workingDirectory: $(System.DefaultWorkingDirectory)

    # Download the tfplan artifact from the Plan stage
    - download: current
      artifact: tfplan
      displayName: 'Download tfplan artifact'

    # Verify downloaded artifact location
    - script: |
        ls -al $(Pipeline.Workspace)/tfplan
      displayName: 'Verify downloaded tfplan'

    # Reinitialize Terraform with the same backend override
    - script: |
        terraform init  \
          -backend-config="storage_account_name=$(storageAccountName)"
      displayName: 'Terraform Init with Lockfile'
      workingDirectory: $(System.DefaultWorkingDirectory)

    # Apply the saved Terraform plan
    - script: |
        terraform apply -auto-approve $(Pipeline.Workspace)/tfplan/tfplan
      displayName: 'Terraform Apply'
      workingDirectory: $(System.DefaultWorkingDirectory)
