# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: MyLinux
  demands:
    - agent.name -equals myAgent

variables:
  group: task-1-variable-group
  resourceGroup: 'Petro_Skaletskyy'
  serviceConnectionName: 'MyServiceConnection'
  sqlAdminPassword: 'P@ssw0rd123!'

stages:
  - stage: 
    displayName: 'Deploy Infrastructure'
    jobs:
      - job: DeployBicep
        displayName: 'Deploy Bicep File'
        steps:
          - task: AzureCLI@2
            displayName: 'Deploy Infrastructure with Azure CLI'
            inputs:
              azureSubscription: $(serviceConnectionName)
              scriptType: bash
              scriptLocation: inlineScript
              inlineScript: |
                az deployment group create \
                  --resource-group $(resourceGroup) \
                  --parameters sqlAdminPassword=$(sqlAdminPassword) \
                  --template-file main.bicep
